name: Europa

on:
  push:
  workflow_dispatch:

jobs:
  europa:
    name: Compile STL
    strategy:
      fail-fast: false
      matrix:
        component:
          - facia
          - top_front
          - top_rear
          - bottom_front
          - bottom_rear
          - screen_retainer_bracket
          - duct
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: "Compile ${{ matrix.component }}"
        uses: addnab/docker-run-action@v3
        with:
          image: matthewbaggett/openscad
          options: -v ${{ github.workspace }}:/src
          run: |
            openscad \
              -o /src/Europa/${{ matrix.component }}.stl \
              -D 'renderPrintablePart="${{ matrix.component }}"' \
              -D 'rotateForPrint="yes"' \
              /src/Europa/rebuilt_europa.scad
      - name: "Store ${{ matrix.component }} artifact."
        uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }}
        with:
          name: Europa - ${{ matrix.component }}
          path: ./Europa/${{ matrix.component }}.stl