name: Rock tumbler

on:
  push:
    paths:
      - 'tumbler.scad'
      - 'Lib'
  workflow_dispatch:

jobs:
  build-tumbler:
    name: Compile STL
    strategy:
      fail-fast: false
      matrix:
        component:
          - front
          - back
          - side
          - left_shaft
          - right_shaft
          - center_carrier
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: "Compile ${{ matrix.component }}"
        uses: addnab/docker-run-action@v3
        with:
          image: bbassett/openscad
          options: -v ${{ github.workspace }}:/src
          run: |
            openscad \
              -o /src/tumbler_${{ matrix.component }}.stl \
              -D 'part="${{ matrix.component }}"' \
              /src/tumbler.scad
      - name: "Store ${{ matrix.component }} artifact."
        uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }}
        with:
          name: Tumbler - ${{ matrix.component }}
          path: ./tumbler_${{ matrix.component }}.stl